### ISSUE TITLE
main.css

### ISSUE THREAD

**Issue by abdellmum** [abdellmum/C2-N2#3]
svp qui ajouté un fichier main.css 
@hmz273 @abdessamadsouilem @Elhilali-hA  notez bien que vous deviez mettre votre style css dans les fichiers css specifié a chaque section et il sera automatiquement ajouté dans un fichier main.css lier au index.html

svp ne toucher pas au fichier starter et ne modifier pas la structure

**Comment by Elhilali-hA** [comment]
fixed
