### ISSUE TITLE
manque de respect d'équipe

### ISSUE THREAD

**Issue by Elhilali-hA** [abdellmum/C2-N2#8]
scrum master orline

**Comment by HananeJab** [comment]
Meeting as soon as possible avec toute l'équipe.

**Comment by abdellmum** [comment]
Normalement ça se discute sur les sprint review

Les issue sont fait pour la partie code seulement 
On a un autre moyen plus privé pour exprimer nos sentiments enver les autres

**Comment by abdellmum** [comment]
Soyez prifessionels  svp
